version: '3.4'

services:

  pixel-test-runner:
    image: pixel-test-runner
    networks:
     - pixel-network
    entrypoint: ["dotnet", "pixel-run.dll", "run", "template", {0}]

networks:
  pixel-network:
    external: true
