version: '3.4'

services:

  firefox-standalone:
    image: selenium/standalone-firefox:latest
    shm_size: 2gb
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "4444"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - {0}

  pixel-test-runner:
    image: pixel-test-runner
    environment:
     - browser=FireFox
     - grid_address=http://firefox-standalone:4444
    networks:
     - pixel-network
     - {0}
    depends_on:
      firefox-standalone:
        condition: service_healthy
    entrypoint: ["dotnet", "pixel-run.dll", "run", "template", {1}]

networks:
  {0}:
    external: true
  pixel-network:
    external: true
